#!/bin/sh

EPGUPD="vsetv2xmltv"
EPGSOURCES="/storage/.config/epgs"
EPGSOURCES_CONF="$EPGSOURCES/config/$EPGUPD"
EPGSOURCES_RES="$EPGSOURCES/resources/$EPGUPD"
PARSER="$EPGSOURCES_RES/vsetv.py"
CHANNELS_FILE="$EPGSOURCES_CONF/channels.cfg"
XMLTV_FILE="/storage/epgsources/xmltv.xml"
DAYS="3"
FDESC="1"

rm -rf /tmp/vsetv
mkdir -p /tmp/vsetv

echo "Running vsetv2xmltv"
python $PARSER $CHANNELS_FILE $XMLTV_FILE $DAYS $FDESC

